[2025-07-23T08:48:12.015+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: openaq_mexico_air_quality_etl.extract_transform_load_openaq_mex manual__2025-07-23T08:48:11.286402+00:00 [queued]>
[2025-07-23T08:48:12.022+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: openaq_mexico_air_quality_etl.extract_transform_load_openaq_mex manual__2025-07-23T08:48:11.286402+00:00 [queued]>
[2025-07-23T08:48:12.023+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-23T08:48:12.034+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_transform_load_openaq_mex> on 2025-07-23 08:48:11.286402+00:00
[2025-07-23T08:48:12.044+0000] {standard_task_runner.py:60} INFO - Started process 871 to run task
[2025-07-23T08:48:12.050+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'openaq_mexico_air_quality_etl', 'extract_transform_load_openaq_mex', 'manual__2025-07-23T08:48:11.286402+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/MexicoairQ_etl_dag.py', '--cfg-path', '/tmp/tmpr75eh3ul']
[2025-07-23T08:48:12.053+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask extract_transform_load_openaq_mex
[2025-07-23T08:48:12.100+0000] {task_command.py:423} INFO - Running <TaskInstance: openaq_mexico_air_quality_etl.extract_transform_load_openaq_mex manual__2025-07-23T08:48:11.286402+00:00 [running]> on host 254e02a0caf4
[2025-07-23T08:48:12.161+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='openaq_mexico_air_quality_etl' AIRFLOW_CTX_TASK_ID='extract_transform_load_openaq_mex' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T08:48:11.286402+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-23T08:48:11.286402+00:00'
[2025-07-23T08:48:12.317+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/MexicoairQ_etl_dag.py", line 15, in etl_openaq_mexico
    resp.raise_for_status()
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.openaq.org/v2/latest?country=MX&limit=100
[2025-07-23T08:48:12.327+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=openaq_mexico_air_quality_etl, task_id=extract_transform_load_openaq_mex, execution_date=20250723T084811, start_date=20250723T084812, end_date=20250723T084812
[2025-07-23T08:48:12.335+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 41 for task extract_transform_load_openaq_mex (410 Client Error: Gone for url: https://api.openaq.org/v2/latest?country=MX&limit=100; 871)
[2025-07-23T08:48:12.383+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-23T08:48:12.398+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
