[2025-07-23T08:00:00.572+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nws_weather_etl.extract_transform_load_nws scheduled__2025-07-23T07:30:00+00:00 [queued]>
[2025-07-23T08:00:00.577+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nws_weather_etl.extract_transform_load_nws scheduled__2025-07-23T07:30:00+00:00 [queued]>
[2025-07-23T08:00:00.577+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-23T08:00:00.586+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_transform_load_nws> on 2025-07-23 07:30:00+00:00
[2025-07-23T08:00:00.590+0000] {standard_task_runner.py:60} INFO - Started process 755 to run task
[2025-07-23T08:00:00.594+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'nws_weather_etl', 'extract_transform_load_nws', 'scheduled__2025-07-23T07:30:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/EE_UUWheater_etl_dag.py', '--cfg-path', '/tmp/tmp6fy4n34n']
[2025-07-23T08:00:00.597+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask extract_transform_load_nws
[2025-07-23T08:00:00.637+0000] {task_command.py:423} INFO - Running <TaskInstance: nws_weather_etl.extract_transform_load_nws scheduled__2025-07-23T07:30:00+00:00 [running]> on host 7896427c6261
[2025-07-23T08:00:00.694+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nws_weather_etl' AIRFLOW_CTX_TASK_ID='extract_transform_load_nws' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T07:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-23T07:30:00+00:00'
[2025-07-23T08:00:31.280+0000] {logging_mixin.py:188} INFO - Error en ETL NWS: mongodb:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6880968153232cd9f0e8c93b, topology_type: Unknown, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2025-07-23T08:00:31.283+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-23T08:00:31.290+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=nws_weather_etl, task_id=extract_transform_load_nws, execution_date=20250723T073000, start_date=20250723T080000, end_date=20250723T080031
[2025-07-23T08:00:31.318+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-23T08:00:31.329+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
