[2025-07-23T08:11:10.002+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk manual__2025-07-23T08:11:08.996614+00:00 [queued]>
[2025-07-23T08:11:10.007+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk manual__2025-07-23T08:11:08.996614+00:00 [queued]>
[2025-07-23T08:11:10.008+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-23T08:11:10.017+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_transform_load_coindesk> on 2025-07-23 08:11:08.996614+00:00
[2025-07-23T08:11:10.022+0000] {standard_task_runner.py:60} INFO - Started process 580 to run task
[2025-07-23T08:11:10.025+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'coindesk_bitcoin_etl', 'extract_transform_load_coindesk', 'manual__2025-07-23T08:11:08.996614+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/coindesk_etl_dag.py', '--cfg-path', '/tmp/tmp9s4j6hog']
[2025-07-23T08:11:10.027+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask extract_transform_load_coindesk
[2025-07-23T08:11:10.067+0000] {task_command.py:423} INFO - Running <TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk manual__2025-07-23T08:11:08.996614+00:00 [running]> on host a1bf3f9b22c7
[2025-07-23T08:11:10.130+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='coindesk_bitcoin_etl' AIRFLOW_CTX_TASK_ID='extract_transform_load_coindesk' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T08:11:08.996614+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-23T08:11:08.996614+00:00'
[2025-07-23T08:11:10.195+0000] {logging_mixin.py:188} INFO - Error en ETL CoinDesk: HTTPSConnectionPool(host='api.coindesk.com', port=443): Max retries exceeded with url: /v1/bpi/currentprice.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x759b4fcf2650>: Failed to resolve 'api.coindesk.com' ([Errno -2] Name or service not known)"))
[2025-07-23T08:11:10.196+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-23T08:11:10.203+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=coindesk_bitcoin_etl, task_id=extract_transform_load_coindesk, execution_date=20250723T081108, start_date=20250723T081110, end_date=20250723T081110
[2025-07-23T08:11:10.237+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-23T08:11:10.250+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
